version: 2.0.{build}
image: Visual Studio 2017

branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.9\msvc2017_64
  - set PATH=%QTDIR%\bin;%PATH%;"

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

before_build:
  - md Output
  - cp CMakeProjectConfig.cmake.example CMakeProjectConfig.cmake
  - md Release

build_script:
  - cd Output
  - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Ninja" "../"
  - cd ../
  - cmake --build Output --target TimeCampDesktop -- -j 2

after_build:
  - copy "Output\TimeCampDesktop.exe" "Release\TimeCampDesktop.exe"
  - copy "src\localdb.sqlite" "Release\localdb.sqlite"
  - windeployqt --release --no-translations Release\TimeCampDesktop.exe
  - copy C:\OpenSSL-Win64\bin\libeay32.dll "Release\libeay32.dll"
  - copy C:\OpenSSL-Win64\bin\ssleay32.dll "Release\ssleay32.dll"

artifacts:
  - path: Release
    type: zip


deploy:
  provider: GitHub
  auth_token:
    secure: 7JiH2SZC0UFwSfd8YsMNcHqENkyCDKSJ5y9TSbIOBbuuClgFnfBdId+5vjysJbjv
  artifact: Release.zip
  draft: false
  prerelease: true
