language: cpp

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
#    cache: ccache #
    # we will revisit ccache later, for now it breaks our builds somehow
    env: SRC="cmake-build-relwithdebinfo" TARGET="linuxdeployqt/TimeCampDesktop.AppDir" CMAKE_NAME="TimeCampDesktop" BUNDLE_NAME="TimeCampDesktop" LinuxDeployQtExec="./linuxdeployqt-continuous-x86_64.AppImage"
  - os: osx
    compiler: clang
    node_js: 8
    env: SRC="cmake-build-relwithdebinfo" TARGET="cmake-build-relwithdebinfo" CMAKE_NAME="TimeCampDesktop" BUNDLE_NAME="TimeCamp Desktop.app" DMG_NAME="TimeCampSetup_macOS.dmg"

git:
  depth: 5
  submodules: false
  quiet: true

branches:
  except:
  - # Do not build tags that we create when we upload to GitHub Releases
  - /^(?i:continuous)/

addons:
  sonarcloud:
    organization: "timecamp-github" # the key of the org you chose at step #3
  homebrew:
    packages:
      - cmake
      - tree
      - ninja
      - qt
#    update: true

before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule sync
- git submodule update --init --recursive
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source ./travis/before_install_linux ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ./travis/before_install_osx ; fi

install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source ./travis/install_linux ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ./travis/install_osx ; fi

before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source ./travis/before_script_linux ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ./travis/before_script_osx ; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source ./travis/script_linux ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ./travis/script_osx ; fi

after_success:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source ./travis/after_success_linux ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ./travis/after_success_osx ; fi

after_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source ./travis/after_script_linux ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ./travis/after_script_osx ; fi

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ${TARGET}/${DMG_NAME}
  skip_cleanup: true
  on:
    condition: $TRAVIS_OS_NAME = osx
    tags: true
