#!/bin/bash -xe

if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    cp $SRC/"${CMAKE_NAME}" $TARGET"/usr/bin/""${BUNDLE_NAME}" # copy the binary
    cp $QTDIR/bin/qtdiag $TARGET"/usr/bin/qtdiag"
    cp res"/${BUNDLE_NAME}.desktop" $TARGET"/usr/share/applications/${BUNDLE_NAME}.desktop" # copy app.desktop file
    cp "res/AppIcon_16.png" $TARGET"/usr/share/icons/hicolor/16x16/${BUNDLE_NAME}.png"
    cp "res/AppIcon_32.png" $TARGET"/usr/share/icons/hicolor/32x32/${BUNDLE_NAME}.png"
    cp "res/AppIcon_48.png" $TARGET"/usr/share/icons/hicolor/48x48/${BUNDLE_NAME}.png"
    cp "res/AppIcon_64.png" $TARGET"/usr/share/icons/hicolor/64x64/${BUNDLE_NAME}.png"
    cp "res/AppIcon_128.png" $TARGET"/usr/share/icons/hicolor/128x128/${BUNDLE_NAME}.png"
    cp "res/AppIcon_256.png" $TARGET"/usr/share/icons/hicolor/256x256/${BUNDLE_NAME}.png"
    unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
    wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
    chmod a+x linuxdeployqt-continuous-x86_64.AppImage
    cp /lib/x86_64-linux-gnu/libssl.so.1.0.0  $TARGET"/usr/lib/"
    cp /lib/x86_64-linux-gnu/libcrypto.so.1.0.0  $TARGET"/usr/lib/"
    cp /lib/x86_64-linux-gnu/libbsd.so.0 $TARGET"/usr/lib/"
    cp -r /usr/lib/x86_64-linux-gnu/nss $TARGET"/usr/lib/"
    export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
    ${LinuxDeployQtExec} $TARGET"/usr/share/applications/${BUNDLE_NAME}.desktop" -bundle-non-qt-libs -extra-plugins=sqldrivers,iconengines -verbose=2
    ${LinuxDeployQtExec} $TARGET"/usr/share/applications/${BUNDLE_NAME}.desktop" -appimage -verbose=2
fi
