#!/bin/sh -xe

if ! brew ls --version cmake &>/dev/null; then
	brew install cmake
else
	brew upgrade cmake
fi

brew install tree
brew install ninja
brew install qt
brew link --force qt
export HOMEBREW_QT5_VERSION=$(brew list --versions qt | rev | cut -d' ' -f1 | rev)
sudo ln -s /usr/local/Cellar/qt/$HOMEBREW_QT5_VERSION/mkspecs /usr/local/mkspecs
sudo ln -s /usr/local/Cellar/qt/$HOMEBREW_QT5_VERSION/plugins /usr/local/plugins

echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile
chmod -R 755 /usr/local/opt/qt/*
