#!/bin/bash -xe

export CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH:/opt/qt59/lib/cmake"

cd $SRC
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Ninja" -DCMAKE_CXX_COMPILER_LAUNCHER=ccache "../"
cd ../

if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    cmake --build $SRC --target "${CMAKE_NAME}" -- # regular build
fi

if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    build-wrapper-linux-x86-64 --out-dir bw_output cmake --build $SRC --target "${CMAKE_NAME}" --
    sonar-scanner # sonar only on non-PRs
fi

tree
