#!/bin/sh -xe

cd $SRC
cmake -DCMAKE_PREFIX_PATH=$(brew --prefix qt) -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Ninja" "../"
cd ../

if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    cmake --build $SRC --target "${CMAKE_NAME}" -- # regular build
fi

if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    # dangerous: look for a binary and execute it
    # Travis gives us no choice as it doesn't link to the wrapper anywhere and doesn't add it to PATH
    macoswrapper=$(find /Users/travis/.sonar/ -perm +111 -type f -name "build-wrapper-macosx*")
    echo $macoswrapper
    $macoswrapper --out-dir bw_output cmake --build $SRC --target "${CMAKE_NAME}" --
    ${SONAR_SCANNER_HOME}/bin/sonar-scanner # sonar only on non-PRs
fi

# tree
